### ISSUE TITLE
Enrichment on positions and islands on a list of genes

### ISSUE THREAD

**Issue by yocra3** [isglobal-brge/EASIER#2]
The current implementation of EASIER only allows running the enrichment test for CpGs islands or gene positions when we have the results for the full array. It will be very useful to run it if we only have a list of CpGs. 

This issue might be solved simply showing how to do this in the vignette.

**Comment by dpelegri** [comment]
Now, with the enrichment script in module_scripts you can set a file with the annotated data or you can set a file with only a list of CpGs. `missMethyl_enrichment` function detects the file type and perform the annotation if necessary in order to proceed with the rest of the enrichment. 
Is this what you mean? or do you mean to be able to pass the CpGs file directly to other functions?
